//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yunchee.Volkswagen.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _1V1MessageWords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _1V1MessageWords() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yunchee.Volkswagen.Common.Resources.1V1MessageWords", typeof(_1V1MessageWords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新的在线询价需要您处理。
        ///客户信息：{0}
        ///昵称：{1}
        ///姓名：{2}
        ///性别：{3}
        ///客户类型：{4}
        ///联络方式：{5}
        ///询价车型：{6}
        ///计划购车时间： {7}
        ///请回复相关数字进行下一步操作：
        ///【1】开始聊天 
        ///【2】查看订单 
        ///【3】查看快捷回复消息指令 
        ///【4】结束聊天 
        ///【5】确认订单 的本地化字符串。
        /// </summary>
        internal static string AskPriceMain {
            get {
                return ResourceManager.GetString("AskPriceMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新的在线咨询消息需要处理。
        ///客户信息：{0}
        ///昵称：{1}
        ///姓名：{2}
        ///性别：{3}
        ///联络方式：{4}
        ///客户类型：{5}
        ///车型：{6}
        ///请回复相关数字进行下一步操作：
        ///1.开始聊天 
        ///2.订单详情 
        ///3.快捷回复消息指令 
        ///4.结束聊天 
        ///5.确认订单 
        ///6.转给服务顾问
        ///如无需聊天请直接回复4结束聊天 的本地化字符串。
        /// </summary>
        internal static string ConsultMain1 {
            get {
                return ResourceManager.GetString("ConsultMain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的在线咨询需要您处理。
        ///客户信息：{0}
        ///昵称：{1}
        ///姓名：{2}
        ///性别：{3}
        ///客户类型：{4}
        ///联络方式：{5}
        ///咨询车型：{6}
        ///计划购车时间： {7}
        ///请回复相关数字进行下一步操作：
        ///【1】开始聊天 
        ///【2】查看订单 
        ///【3】查看快捷回复消息指令 
        ///【4】结束聊天 
        ///【5】确认订单 的本地化字符串。
        /// </summary>
        internal static string ConsultMain2 {
            get {
                return ResourceManager.GetString("ConsultMain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的试驾预约需要您处理。
        ///预约试驾信息：
        ///昵称：{0}
        ///姓名：{1}
        ///性别：{2}
        ///客户类型：{3}
        ///联络方式：{4}
        ///试驾车型：{5}
        ///计划购车时间：{6}
        ///预约试驾时间： {7}
        ///请回复相关数字进行下一步操作：
        ///【1】开始聊天 
        ///【2】查看订单 
        ///【3】查看快捷回复消息指令 
        ///【4】结束聊天 
        ///【5】确认订单 的本地化字符串。
        /// </summary>
        internal static string DriveMain {
            get {
                return ResourceManager.GetString("DriveMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有其他工作人员在处理 的本地化字符串。
        /// </summary>
        internal static string Input1Error1 {
            get {
                return ResourceManager.GetString("Input1Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已超过48小时无法与客户进行聊天 的本地化字符串。
        /// </summary>
        internal static string Input1Error2 {
            get {
                return ResourceManager.GetString("Input1Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以开始对话，请输入文字或图片进行聊天。 的本地化字符串。
        /// </summary>
        internal static string Input1Success {
            get {
                return ResourceManager.GetString("Input1Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 询价客户信息：
        ///昵称：{0}
        ///姓名：{1}
        ///性别：{2}
        ///客户类型：{3}
        ///联络方式：{4}
        ///询价车型：{5}
        ///计划购车时间：{6} 的本地化字符串。
        /// </summary>
        internal static string Input2AskPrice {
            get {
                return ResourceManager.GetString("Input2AskPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户信息：
        ///昵称：{0}
        ///姓名：{1}
        ///性别：{2}
        ///客户类型：{3}
        ///联络方式：{4} 的本地化字符串。
        /// </summary>
        internal static string Input2Consult {
            get {
                return ResourceManager.GetString("Input2Consult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预约试驾订单信息：
        ///昵称：{0}
        ///姓名：{1}
        ///性别：{2}
        ///联络方式：{3}
        ///试驾车型：{4}
        ///计划购车时间：{5}
        ///预约试驾时间：{6} 的本地化字符串。
        /// </summary>
        internal static string Input2Drive {
            get {
                return ResourceManager.GetString("Input2Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预约保养订单信息：
        ///昵称：{0}
        ///姓名：{1}
        ///性别：{2}
        ///客户类型：{3}
        ///联络方式：{4}
        ///车型：{5}
        ///车牌号：{6}
        ///上次保养时间：{7}
        ///上次保养公里数：{8}
        ///预约时间：{9}
        ///保养项目：{10} 的本地化字符串。
        /// </summary>
        internal static string Input2Maintance {
            get {
                return ResourceManager.GetString("Input2Maintance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预约维修订单信息：
        ///昵称：{0}
        ///姓名：{1}
        ///性别：{2}
        ///客户类型：{3}
        ///联络方式：{4}
        ///车型：{5}
        ///车牌号：{6}
        ///维修原因：{7} 的本地化字符串。
        /// </summary>
        internal static string Input2Repair {
            get {
                return ResourceManager.GetString("Input2Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新的保养订单消息需要处理。
        ///客户信息：{0}
        ///姓名：{1}
        ///性别：{2}
        ///客户类型：{3}
        ///联络方式：{4}
        ///车型：{5}
        ///车牌号：{6}
        ///上次保养时间：{7}
        ///上次保养公里数：{8}
        ///预约保养时间：{9}
        ///保养项目：{10}
        ///请回复相关数字进行下一步操作：
        ///1.开始聊天 
        ///2.订单详情 
        ///3.快捷回复消息指令 
        ///4.结束聊天 
        ///5.确认订单  
        ///6.转给服务顾问
        ///如无需聊天请回复4结束聊天再回复5确认订单。 的本地化字符串。
        /// </summary>
        internal static string MaintanceMain {
            get {
                return ResourceManager.GetString("MaintanceMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新的维修订单消息需要处理。
        ///客户信息：{0}
        ///姓名：{1}
        ///性别：{2}
        ///客户类型：{3}
        ///联络方式：{4}
        ///车型：{5}
        ///车牌号：{6}
        ///维修原因：{7}
        ///请回复相关数字进行下一步操作：
        ///1.开始聊天 
        ///2.订单详情 
        ///3.快捷回复消息指令 
        ///4.结束聊天 
        ///5.确认订单  
        ///6.转给服务顾问
        ///如无需聊天请回复4结束聊天再回复5确认订单。 的本地化字符串。
        /// </summary>
        internal static string RepairMain {
            get {
                return ResourceManager.GetString("RepairMain", resourceCulture);
            }
        }
    }
}
